### ISSUE TITLE
column mismatch when there are empty cells

### ISSUE THREAD

**Issue by amzoss** [fureweb-com/public-google-sheets-parser#14]
I love this so far! But I have some data where there are empty cells in some rows, and the parser seems to skip over the nulls when it associates the values with columns for each row. I can't tell by looking if `filterUselessRows` is removing all nulls in each row, even if there are some data values, or if it's something else.

Let me know if you'd like me to provide more details, but I think it's pretty easy to confirm. (For example, compare [Sample data](https://docs.google.com/spreadsheets/d/1m55mK6IVJxs9PEjX8i90VB8uy8eLkmv_F04iR7v6spc/edit?usp=sharing) to results when using spreadsheet ID `1m55mK6IVJxs9PEjX8i90VB8uy8eLkmv_F04iR7v6spc` in [Demo Site](http://fureweb.com/public-google-sheets-parser.html). Column headers are wrong for rows 2 and 3. )

Thanks for considering!

**Comment by fureweb-com** [comment]
Thanks for letting me know about the issue. I'll check it out.
