### ISSUE TITLE
Wrong json?

### ISSUE THREAD

**Issue by dcromster** [fureweb-com/public-google-sheets-parser#16]
Hello!

I just parse this google sheet: https://docs.google.com/spreadsheets/d/1zCHUcpJI6KPwHNoZttTopJ7zHLF31bfb7HgsIodsqyg/edit#gid=0

and receive wrong JSON:
`[
  {
    '1 урок': '4 урок',
    '5б': '6в',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'Яковлева К.В. (замещение математики)',
    '': 11
  },
  {
    '1 урок': '5 урок',
    '5б': '7а',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'математика, Сергеева Н.И. (замещение)',
    '': 48
  },
  {
    '5б': '9а',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  {
    '1 урок': '6 урок',
    '5б': '6б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  {
    '1 урок': '7 урок',
    '5б': '6а, 7а ',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  { '1 урок': 'Отсутствует: Яковлева Т.В.' },
  {
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': '20 сентября, вторник'
  },
  {
    '1 урок': '4 урок',
    '5б': '8б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'физика, Котова Н.И. вместо 7 урока',
    '': 45
  },
  {
    '1 урок': '5 урок',
    '5б': '8а',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'биология, Калинина Л.М. (замещение технологии)',
    '': 35
  },
  {
    '1 урок': '7 урок ',
    '5б': '8б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  { '1 урок': 'Отсутствует: Иванов М.С.' },
  {
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': '21 сентября, среда'
  },
  {
    '1 урок': '4 урок',
    '5б': '9б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'Головко А.Б. вместо 5а класса',
    '': 9
  },
  {
    '1 урок': '6 урок',
    '5б': '9б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'Скрипка Н.В. вместо 5а класса',
    '': 32
  },
  { '1 урок': 'Отсутствует: Рольгейзер К.С.' },
  {
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': '23 сентября, пятница'
  },
  {
    '1 урок': '2 урок',
    '5б': '9б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'математика, Сергеева Н.И. (замещение истории)',
    '': 48
  },
  {
    '1 урок': '4 урок',
    '5б': '6в',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'русский язык, Белова С.Н. (замещение истории)',
    '': 41
  },
  {
    '1 урок': '5 урок',
    '5б': '6б',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'русский язык, Кутушева Н.Д. (замещение истории)',
    '': 29
  },
  {
    '1 урок': '6 урок',
    '5б': '6а',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  {
    '1 урок': '7 урок',
    '5б': '9а',
    'Изменения в расписании уроков 19 сентября, понедельник к 3 уроку': 'домой'
  },
  { '1 урок': 'Отсутствует: Рольгейзер К.С.' }
]
`

code:`const PublicGoogleSheetsParser = require('public-google-sheets-parser')

const spreadsheetId = '1zCHUcpJI6KPwHNoZttTopJ7zHLF31bfb7HgsIodsqyg'

// 1. You can pass spreadsheetId when parser instantiation
const parser = new PublicGoogleSheetsParser(spreadsheetId)
parser.parse().then((items) => {
    console.log(items);
  // items should be [{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]
})`

What I do wrong?

**Comment by fureweb-com** [comment]
Hello. First of all, thank you for posting the issue.

I checked your Google spreadsheet but in conclusion, it cannot be parsed.

To get the data you want from this library,
1) the first column must be a header.
2) All subsequent columns must be populated with values corresponding to the header.

If the above conditions are not met, Google Spread Sheet cannot be used parsed via this library.

If you have any additional questions, please add comments to this post.

**Comment by dcromster** [comment]
Thank You for fast reply!

No, I have no more questions.
