### ISSUE TITLE
Columns with Falsey values won't get returned in item, but I would like them to

### ISSUE THREAD

**Issue by MarioKrstevski** [fureweb-com/public-google-sheets-parser#31]
Hi, this is maybe not an issue but a feature. When I have values in my columns like FALSE, 0 they don't get returned, so the items that I get back don't have that Column at all.  

Or if some values in the Column are with numbers, and one of them is TRUE/FALSE, the true-false value doesn't get pulled back also

Since I am using conditional logic on my React based on that value I would like to have them, can someone guide me on how to do this? 

The simplest way is to treat everything as text, is there an option for this or maybe an option in Google Sheets I can set for this

Use case: Keeping track of items that are in stock. 
Works fine if we have items in stock (1,4,55,..) but once we get to 0, the value I get is basically undefined (key doesnt exist at all for that item) and I would like to have 0.  And based on it  I would like to do my conditionals.

Use case 2: I have a toggle for a button and sometimes it expects true/false based on the item

I can work around my logic for myself, but I am making an app maker (people use my app to make apps) so my selection logic has to be dynamic and they should decide when something is disabled, based on pattern matching for string. So sometimes I need the 0 or the FALSE as a response instead of the whole key being omitted.

Is there a setting for this or should I fallback and try to use the  underlying fetch for this myself
https://docs.google.com/spreadsheets/d/{sheetID}/gviz/tq?

**Comment by MarioKrstevski** [comment]
Sure man, https://docs.google.com/spreadsheets/d/1_9YFfrJ9WDHMGEG0JUy2PSdZMgheqQuoTtfOsppyTgE/edit#gid=0, but I tested it and your lib doesn't cover this. 

I did my own workaround with the code and a second trick someone can use is to do the Select Cells > Format > Number > Plain text and all will be a string type

I know sheets wasn't intended for this but I'm using it as a CMS and lets say I have a ratings value and someone enters a value like 4/5, well for Spreadsheets that's automatically converted to a date lol, well this is the same type of problem.

**Comment by cjmling** [comment]
I have the same issue. Only checkbox with true value get returned

**Comment by thienhaflash** [comment]
Please get it merged @fureweb-com 
I got the same problem - whenever the value is 0 or false it disappeared from the result. The fix is as simple as `do not use .v to check for existing value`
