### ISSUE TITLE
useFormat not returning value as string.

### ISSUE THREAD

**Issue by mnkrome** [fureweb-com/public-google-sheets-parser#45]
Heres my [Spreadsheet](https://docs.google.com/spreadsheets/d/1MycYMkH_NNhvks108-x_UIz-6OVAkoVTZeacUXOPYcU/edit?usp=sharing) for reference.

The cash values returns as '500' for all my entries; instead of $500 like in the sheet.

Dunno if its a bug or am I doing something wrong?

**Comment by fureweb-com** [comment]
Now that I've checked, the value in the cash field seems to be displaying as "$500" as expected, is there a problem?

Did you apply the useFormat option?

![Screenshot_20240312_075521_Samsung Internet.jpg](https://github.com/fureweb-com/public-google-sheets-parser/assets/22983900/d8e8cf23-7211-449a-a9cf-3566c1555fcf)

![Screenshot_20240312_075514_Samsung Internet.jpg](https://github.com/fureweb-com/public-google-sheets-parser/assets/22983900/608c3439-196f-49a1-8924-da9c253cb03a)

**Comment by mnkrome** [comment]
yup! Heres my code

    const PublicGoogleSheetsParser = require('public-google-sheets-parser')
    var spreadsheetId  = this.GetInputValue("data", cache) || this.GetOptionValue("data", cache); 
    const sheetname  = this.GetInputValue("sheet", cache) || this.GetOptionValue("sheet", cache); 
    const string = this.GetOptionValue("string", cache);     

    if(spreadsheetId.includes("/")){
        const regex = /\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/;
        const match = spreadsheetId.match(regex);
        spreadsheetId = match[1]
    }

    let  option = { useFormat: string };
    if (sheetname) { option.sheetName = sheetname }
    const parser = new PublicGoogleSheetsParser(spreadsheetId, option)
    const table = await parser.parse()
    
    i even used the direct option like
 const parser = new PublicGoogleSheetsParser(spreadsheetId, { useFormat: true })
and still get only 500
![image_2024-03-11_220812630](https://github.com/fureweb-com/public-google-sheets-parser/assets/76726629/9b763d57-1f1e-4169-8f06-cc18cf4a379b)

**Comment by fureweb-com** [comment]
I just finished testing and if it's 1.5, it should work fine when using the useFormat option.

In my tests, it worked fine.

Is it possible to put the below example code in your project to show the result?

Please provide a screenshot or copy & paste to show the result of checking the value of data.

https://github.com/fureweb-com/public-google-sheets-parser?tab=readme-ov-file#example-with-options

**Comment by mnkrome** [comment]
Oh I figured my error! The NPM didnt update correctly, had to re-start the project and download again. Thank you so much and sorry for the trouble!!
