### ISSUE TITLE
Missing characters on parsed data ");"

### ISSUE THREAD

**Issue by umutakmak** [fureweb-com/public-google-sheets-parser#50]
My google sheet includes some html tags and some function names or some rgb values on some of them. If google sheets has any of this combination of characters `);` (a closing parenthesis followed by a semicolon) it is not included in the parsed results. Just ignores and skips that characters. Probably some parsing error?

Here are some examples:
`<a style="color: rgb(218, 218, 218); font-weight: bold;" href="/policy/website/terms-of-service" target="_blank">` 
becomes 
`<a style="color: rgb(218, 218, 218 font-weight: bold;" href="/policy/website/terms-of-service" target="_blank">`
As you can see the characters at the end of the rgb values are gone. 

Smaller examples again works:
`rgb(218, 218, 218);` becomes `rgb(218, 218, 218`
`"CallSomeFunction();"` becomes `"CallSomeFunction("`
`CallSomeFunction();` becomes `CallSomeFunction(`

I am using this on node.js v20.11.0
public-google-sheets-parser v1.5.2
Every other text and characters seems to work fine.

**Comment by fureweb-com** [comment]
Thanks for the report, I've released it to version 1.5.3, can you check if it works?

**Comment by umutakmak** [comment]
Yes it works! This was faster than a pizza delivery. Thank you...
