### ISSUE TITLE
outdated SheetInfo types

### ISSUE THREAD

**Issue by cjmling** [fureweb-com/public-google-sheets-parser#52]
It seems new property are now allowed for SheetInfo (such as useFormatDate) but `index.d.ts` isn't yet updated with this option yet. 

![image](https://github.com/fureweb-com/public-google-sheets-parser/assets/1612187/20956e8c-2373-4e78-ad63-52ce34092a80)

**Comment by fureweb-com** [comment]
I just released it to [v1.5.4](https://github.com/fureweb-com/public-google-sheets-parser/releases/tag/v1.5.4), let me know if you notice anything weird!
Thanks.
