### ISSUE TITLE
Data is overridden if two columns have the same header name

### ISSUE THREAD

**Issue by zsebedits** [fureweb-com/public-google-sheets-parser#56]
### Problem

Data is overridden if two columns have the same header name. If two columns have the same header name, only the value of the last column with this name is returned. Some sheets use the same column name multiple times for displaying nested information, so it might be useful to find a way to return all columns, even if the name is the same.

### Example

This sheet (https://docs.google.com/spreadsheets/d/1ZjNQ-MB660qU8dwxFNVxLxUBfiZr1IW-XoDkngtqZRY/edit?usp=sharing) produces the following result:

uniqueColumn | sameColumn | sameColumn
-- | -- | --
Unique 1 | Same 1 | Same 2

```json
[
  {
    "uniqueColumn": "Unique 1",
    "sameColumn": "Same 2"
  }
]
````

### Possible Fixes

There could be an optional flag in the configuration to also include the column identifier (A, B, ...) in the response, for example `A - uniqueColumn`, `B - sameColumn`, `C - sameColumn`.

**Comment by fureweb-com** [comment]
Hello,

I appreciate you highlighting this issue and providing your feedback.

I understand that this library is designed to use Google Spreadsheets as database tables, and it's a common use case to have unique column names in a table.

After careful consideration, I believe that adding code to handle duplicate column names may not provide significant benefits, as it deviates from the standard practice of having distinct column names in a table.

Instead, I suggest structuring the spreadsheet with unique column names to align with the intended usage of the library. This approach would ensure smoother integration and avoid potential conflicts.

If you have any further concerns or disagreements, please feel free to add your comments, and we can discuss them further.

For now, I will proceed with closing this issue.

Thank you for your understanding and cooperation!

Best regards,
