### ISSUE TITLE
Demo Page: Column headers misidentified as being from Row 2

### ISSUE THREAD

**Issue by diabWH3** [fureweb-com/public-google-sheets-parser#9]
The [demo page](http://fureweb.com/public-google-sheets-parser.html) incorrectly identifies header info as coming from Row 2. Is this fixed in the GitHub codebase?

I'm testing with spreadsheet ID: [1e__K3V5XOzhCXqXDn9DtY_5k4OwoIxPBfzPr1-UFnOQ](https://docs.google.com/spreadsheets/d/1e__K3V5XOzhCXqXDn9DtY_5k4OwoIxPBfzPr1-UFnOQ/edit?usp=sharing)

**Comment by fureweb-com** [comment]
Hello diabWH3.

I checked, but it doesn't seem to have any problems.

Could you please explain in more detail which part is the problem?

<img width="604" alt="image" src="https://user-images.githubusercontent.com/22983900/109414141-aa3c6d00-79f4-11eb-9cfd-b30455835b1d.png">

**Comment by diabWH3** [comment]
It works now, so an update must've been pushed out.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
